import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AnimatedBG from "./component/elements/AnimatedBG/AnimatedBG";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VJB Studio - Digital Launchpad",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} relative min-h-screen antialiased bg-black`}
      >
        <div className="md:absolute fixed top-0 left-0 w-full h-full z-7">
          <AnimatedBG />
        </div>
        <video
          autoPlay
          loop
          muted
          className="md:absolute fixed top-0 left-0 w-full h-full object-cover z-5 bg-black"
        >
          <source src={"/bgvid.webm"} type="video/webm" />
          <source src={"/bgvid.mp4"} type="video/mp4" />
        </video>
        <div className="md:absolute fixed top-0 left-0 w-full h-full z-6 bg-black/65 backdrop-blur-sm" />
        <div className="relative z-10 min-h-screen">{children}</div>
      </body>
    </html>
  );
}
